### ISSUE TITLE
URL主机部分不支持localhost吗

### ISSUE THREAD

**Issue by greenlgy** [sunyue1380/QuickHttp2#1]
URL主机部分只能是域名或者IP地址， 不支持localhost吗？ 用localhost报错。

**Comment by sunyue1380** [comment]
我明白了，代码里面有一个关于获取顶级域的逻辑，使用localhost这段代码会报错误。
我等下会修复这个问题，然后发布一个小版本2.0.5.1。

**Comment by sunyue1380** [comment]
2.0.5.1已经发布到中央仓库了。使用localhost也可以正常访问了，感谢反馈。

**Comment by greenlgy** [comment]
速度！！ 赞！！
